### ISSUE TITLE
Incorrect withQueryStringItem in README.md

### ISSUE THREAD

**Issue by gsscoder** [owainlewis/yfinance#2]
Form README.md the signature seems to be accept two string and a request, but it really needs a NameValue record.

Anyway, thanks for sharing this great lib!

Giacomo

**Comment by owainlewis** [comment]
Ah thanks. Yeah it's changed a bit. Will update. Thanks :+1:

**Comment by gsscoder** [comment]
Perfect, just to report it! :)

So I leave up to you to close the issue as a reminder.

Thanks again for your work.

**Comment by gsscoder** [comment]
Sorry! I thin I was posting on Http.fs!!! Please forgive me... The fact is that I'm exceisizing myself in porting yfinance to F#!

I'm so sorry to disturbing you... :(

Giacomo.

**Comment by gsscoder** [comment]
I was writing here, because I was working on porting your lib to F#. Just finished:
https://github.com/gsscoder/YFinance.fs.

:)

**Comment by owainlewis** [comment]
Very nice : ) :+1:

**Comment by gsscoder** [comment]
Thanks! It was a cool thing doing it... Thanks for the original! :)

**Comment by gsscoder** [comment]
Just for curiosity of see things in different languages, I've ported the **F# port** of your Haskell to LFE (ErlangLISP): [repo here](https://github.com/gsscoder/yfinance-lfe).

Haskell -> F# -> Functional Lisp dialect

:)
